export const GET_ANNOUNCEMENTS =  'GET_ANNOUNCEMENTS';
export const ADD_ANNOUNCEMENT =  'ADD_ANNOUNCEMENT';
export const DELETE_ANNOUNCEMENT =  'DELETE_ANNOUNCEMENT';
export const ANNOUNCEMENTS_LOADING =  'ANNOUNCEMENTS_LOADING';
export const GET_FEEDBACK = 'GET_FEEDBACK';
export const FEEDBACK_LOADING = 'FEEDBACK_LOADING';